sudo: required
services:
- docker
before_install:
- docker build -t scottduller/esrs-server -f Dockerfile.dev .
script:
- docker run scottduller/esrs-server yarn test
deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: esrs-project
  env: Esrsproject-env
  bucket_name: elasticbeanstalk-eu-west-2-923573125615
  bucket_path: esrs-project
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"